import React from 'react';

//Don't need createClass, Components are stateless
//Hurray for good design

const <%= pageName %>Component = ({ onTextChange, text, fullStore }) => (
    <div className="container">
        <div className="row">
            <div className="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <h1>{text}</h1>
            <p>This page was autogenerated for you.<br />The following steps were taken:</p>
            <ul>
                <li>A component <%= pageName %>Component.jsx was created. That's this file right here!</li>
                <li>A container <%= pageName %>Container.jsx was created. That's the container partial.</li>
                <li>A reducer <%= pageName %>Reducer.js was created, and combined in the main reducer file.</li>
                <li>A store variable <%= pageName %> was added to the createStore method in the store.</li>
                <li>An action <%= pageName %>Action.js was created, and added to <%= pageName %>Reducer.js</li>
                <li>A route was automatically created and placed within routes.jsx </li>
                <li>That route was directly added to CoreLayout.jsx</li>
            </ul>
            <h2>Next Steps:</h2>
            <ul>
                <li>Substitute your logo in CoreLayout.jsx</li>
                <li>Add visual elements to <%= pageName %>Component.jsx (like forms and stuff).</li>
                <li>Add application logic to <%= pageName %>Container.jsx (network requests, validation)</li>
                <li>Create extra custom reducers using api.js -> customReducer. Use customAction as well! </li>
                <li>Combine these reducers in the main reducer.js file.</li>
            </ul>
            </div>
            <div className="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <h3>Type something in here to change the article title!</h3>
                <input type="text" className="form-control" onChange={onTextChange} value={text}></input>
                <h1>This is what the store looks like:</h1>
                <pre>{fullStore}</pre>
            </div>
        </div>
    </div>
);

export default <%= pageName %>Component;